language: minimal
services:
- docker
script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- chmod +x buildImages.sh && ./buildImages.sh
- chmod +x pushImagesReleaseCandidate.sh && ./pushImagesReleaseCandidate.sh
#- cd infrastructure-tests && chmod +x runTests.sh && ./runTests.sh
